"""
Segmentation Validation Script
Converted from val_mask.ipynb
Evaluates a trained segmentation head on validation data and saves predictions
"""

import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
from torch import nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
import torchvision.transforms as transforms
from PIL import Image
import cv2
import os
import argparse
import json
from tqdm import tqdm

plt.switch_backend('Agg')

# ============================================================================
# Utility Functions
# ============================================================================

def save_image(img, filename):
    img = np.array(img)
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    img = np.moveaxis(img, 0, -1)
    img = (img * std + mean) * 255
    img = np.clip(img, 0, 255).astype(np.uint8)
    cv2.imwrite(filename, img[:, :, ::-1])

# ============================================================================
# Mask Conversion
# ============================================================================

DEFAULT_VALUE_MAP = {
    0: 0,
    100: 1,
    200: 2,
    300: 3,
    500: 4,
    550: 5,
    700: 6,
    800: 7,
    7100: 8,
    10000: 9
}
value_map = DEFAULT_VALUE_MAP.copy()
mapping_mode = "int"

class_names = [
    'Background', 'Trees', 'Lush Bushes', 'Dry Grass', 'Dry Bushes',
    'Ground Clutter', 'Logs', 'Rocks', 'Landscape', 'Sky'
]

n_classes = len(value_map)

def build_color_palette(num_classes):
    base = np.array([
        [0, 0, 0],
        [34, 139, 34],
        [0, 255, 0],
        [210, 180, 140],
        [139, 90, 43],
        [128, 128, 0],
        [139, 69, 19],
        [128, 128, 128],
        [160, 82, 45],
        [135, 206, 235],
    ], dtype=np.uint8)

    if num_classes <= len(base):
        return base[:num_classes]

    rng = np.random.default_rng(42)
    extra = rng.integers(0, 255, size=(num_classes - len(base), 3), dtype=np.uint8)
    return np.vstack([base, extra])


color_palette = build_color_palette(n_classes)


def load_value_map(mapping_json_path):
    """Load mapping JSON generated by generate_mask_mapping.py."""
    with open(mapping_json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    mode = data.get("mode", "int")
    raw_mapping = data.get("mapping", {})
    parsed = {}

    if mode == "rgb":
        for key, value in raw_mapping.items():
            rgb = tuple(int(x) for x in str(key).split(","))
            if len(rgb) != 3:
                raise ValueError(f"Invalid RGB key in mapping: {key}")
            parsed[rgb] = int(value)
    else:
        for key, value in raw_mapping.items():
            parsed[int(key)] = int(value)

    if not parsed:
        raise ValueError("Loaded mapping is empty")

    return parsed, mode


def set_value_map(new_map, mode):
    """Update global mask mapping and derived class metadata."""
    global value_map, n_classes, mapping_mode, class_names, color_palette
    value_map = new_map
    n_classes = len(new_map)
    mapping_mode = mode
    class_names = [f"Class_{i}" for i in range(n_classes)]
    color_palette = build_color_palette(n_classes)

def convert_mask(mask):
    arr = np.array(mask)
    if mapping_mode == "rgb":
        if arr.ndim == 2:
            arr = np.stack([arr, arr, arr], axis=-1)
        if arr.shape[2] > 3:
            arr = arr[:, :, :3]

        new_arr = np.zeros(arr.shape[:2], dtype=np.uint8)
        for raw_value, new_value in value_map.items():
            rgb = np.array(raw_value, dtype=arr.dtype)
            new_arr[np.all(arr == rgb, axis=-1)] = new_value
    else:
        if arr.ndim == 3:
            arr = arr[:, :, 0]
        new_arr = np.zeros_like(arr, dtype=np.uint8)
        for raw_value, new_value in value_map.items():
            new_arr[arr == raw_value] = new_value

    return Image.fromarray(new_arr)

def mask_to_color(mask):
    h, w = mask.shape
    color_mask = np.zeros((h, w, 3), dtype=np.uint8)
    for class_id in range(n_classes):
        color_mask[mask == class_id] = color_palette[class_id]
    return color_mask

# ============================================================================
# Dataset
# ============================================================================

class MaskDataset(Dataset):
    def __init__(self, data_dir, transform=None, mask_transform=None):
        self.image_dir = os.path.join(data_dir, 'Color_Images')
        self.masks_dir = os.path.join(data_dir, 'Segmentation')
        self.transform = transform
        self.mask_transform = mask_transform
        self.data_ids = sorted(os.listdir(self.image_dir))

    def __len__(self):
        return len(self.data_ids)

    def __getitem__(self, idx):
        data_id = self.data_ids[idx]
        img_path = os.path.join(self.image_dir, data_id)
        mask_path = os.path.join(self.masks_dir, data_id)

        image = Image.open(img_path).convert("RGB")
        mask = Image.open(mask_path)
        mask = convert_mask(mask)

        if self.transform:
            image = self.transform(image)
            mask = self.mask_transform(mask) * 255

        return image, mask, data_id

# ============================================================================
# Model
# ============================================================================

class SegmentationHeadConvNeXt(nn.Module):
    def __init__(self, in_channels, out_channels, tokenW, tokenH):
        super().__init__()
        self.H, self.W = tokenH, tokenW

        self.stem = nn.Sequential(
            nn.Conv2d(in_channels, 128, kernel_size=7, padding=3),
            nn.GELU()
        )

        self.block = nn.Sequential(
            nn.Conv2d(128, 128, kernel_size=7, padding=3, groups=128),
            nn.GELU(),
            nn.Conv2d(128, 128, kernel_size=1),
            nn.GELU(),
        )

        self.classifier = nn.Conv2d(128, out_channels, 1)

    def forward(self, x):
        B, N, C = x.shape
        x = x.reshape(B, self.H, self.W, C).permute(0, 3, 1, 2)
        x = self.stem(x)
        x = self.block(x)
        return self.classifier(x)

# ============================================================================
# Metrics
# ============================================================================

def compute_iou(pred, target, num_classes=10):
    pred = torch.argmax(pred, dim=1)
    pred, target = pred.view(-1), target.view(-1)

    iou_per_class = []
    for class_id in range(num_classes):
        pred_inds = pred == class_id
        target_inds = target == class_id

        intersection = (pred_inds & target_inds).sum().float()
        union = (pred_inds | target_inds).sum().float()

        if union == 0:
            iou_per_class.append(np.nan)
        else:
            iou_per_class.append((intersection / union).cpu().numpy())

    return np.nanmean(iou_per_class), iou_per_class

def compute_dice(pred, target, num_classes=10, smooth=1e-6):
    pred = torch.argmax(pred, dim=1)
    pred, target = pred.view(-1), target.view(-1)

    dice_per_class = []
    for class_id in range(num_classes):
        pred_inds = pred == class_id
        target_inds = target == class_id

        intersection = (pred_inds & target_inds).sum().float()
        dice = (2 * intersection + smooth) / (
            pred_inds.sum().float() + target_inds.sum().float() + smooth
        )
        dice_per_class.append(dice.cpu().numpy())

    return np.mean(dice_per_class), dice_per_class

def compute_pixel_accuracy(pred, target):
    pred_classes = torch.argmax(pred, dim=1)
    return (pred_classes == target).float().mean().cpu().numpy()

# 🔹 mAP@0.5 ADDITION
def compute_map50(pred, target, num_classes=10, iou_threshold=0.5):
    pred_classes = torch.argmax(pred, dim=1)
    ap_per_class = []

    for class_id in range(num_classes):
        pred_mask = (pred_classes == class_id)
        gt_mask = (target == class_id)

        intersection = (pred_mask & gt_mask).sum().float()
        union = (pred_mask | gt_mask).sum().float()

        if union == 0:
            ap_per_class.append(np.nan)
            continue

        iou = intersection / union
        ap = 1.0 if iou >= iou_threshold else 0.0
        ap_per_class.append(ap)

    return np.nanmean(ap_per_class), ap_per_class

# ============================================================================
# Main
# ============================================================================

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))

    parser = argparse.ArgumentParser()
    parser.add_argument('--model_path', type=str, default=os.path.join(script_dir, 'segmentation_head.pth'))
    parser.add_argument('--data_dir', type=str, default=os.path.join(script_dir, '..', 'Offroad_Segmentation_testImages'))
    parser.add_argument('--output_dir', type=str, default='./predictions')
    parser.add_argument('--batch_size', type=int, default=2)
    parser.add_argument('--num_workers', type=int, default=0)
    parser.add_argument('--mapping_json', type=str, default='', help='Optional mapping JSON generated by generate_mask_mapping.py')
    args = parser.parse_args()

    if args.mapping_json:
        loaded_map, loaded_mode = load_value_map(args.mapping_json)
        set_value_map(loaded_map, loaded_mode)
        print(f"Loaded mapping from {args.mapping_json} | mode={mapping_mode} | classes={n_classes}")
    else:
        print(f"Using default mapping | mode={mapping_mode} | classes={n_classes}")

    os.makedirs(args.output_dir, exist_ok=True)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")

    w = int(((960 / 2) // 14) * 14)
    h = int(((540 / 2) // 14) * 14)

    transform = transforms.Compose([
        transforms.Resize((h, w)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    mask_transform = transforms.Compose([
        transforms.Resize((h, w), interpolation=transforms.InterpolationMode.NEAREST),
        transforms.ToTensor(),
    ])

    valset = MaskDataset(args.data_dir, transform, mask_transform)
    val_loader = DataLoader(valset, batch_size=args.batch_size, shuffle=False, num_workers=args.num_workers)

    backbone = torch.hub.load("facebookresearch/dinov2", "dinov2_vits14").to(device).eval()

    sample_img, _, _ = valset[0]
    with torch.no_grad():
        embed = backbone.forward_features(sample_img.unsqueeze(0).to(device))["x_norm_patchtokens"]
    n_embed = embed.shape[2]

    classifier = SegmentationHeadConvNeXt(
        n_embed, n_classes, w // 14, h // 14
    ).to(device)
    classifier.load_state_dict(torch.load(args.model_path, map_location=device))
    classifier.eval()

    iou_scores, dice_scores, pixel_accs = [], [], []
    map50_scores, all_class_map50 = [], []

    with torch.no_grad():
        for imgs, labels, _ in tqdm(val_loader):
            imgs, labels = imgs.to(device), labels.to(device)
            feats = backbone.forward_features(imgs)["x_norm_patchtokens"]
            logits = classifier(feats)
            outputs = F.interpolate(logits, size=imgs.shape[2:], mode="bilinear", align_corners=False)

            labels = labels.squeeze(1).long()

            iou, _ = compute_iou(outputs, labels, num_classes=n_classes)
            dice, _ = compute_dice(outputs, labels, num_classes=n_classes)
            pixel = compute_pixel_accuracy(outputs, labels)
            map50, class_map50 = compute_map50(outputs, labels, num_classes=n_classes)

            iou_scores.append(iou)
            dice_scores.append(dice)
            pixel_accs.append(pixel)
            map50_scores.append(map50)
            all_class_map50.append(class_map50)

    print("\n===== FINAL RESULTS =====")
    print(f"Mean IoU   : {np.mean(iou_scores):.4f}")
    print(f"mAP@0.5   : {np.mean(map50_scores):.4f}")
    print(f"Pixel Acc : {np.mean(pixel_accs):.4f}")

if __name__ == "__main__":
    main()