"""
Segmentation training script for Falcon desert hackathon dataset.

Upgrades included:
- Correct default class mapping for Falcon class IDs
- Joint image/mask augmentations
- Optional auto class weighting for imbalance
- Mixed precision support (CUDA)
- Learning-rate scheduler + early stopping
- Best-checkpoint export and richer training artifacts
"""

import argparse
import csv
import json
import os
import random
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn.functional as F
import torchvision.transforms as transforms
from PIL import Image, ImageOps
from torch import nn
from torch.optim import AdamW, SGD
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm


plt.switch_backend("Agg")

IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"}
IGNORE_INDEX = 255

DEFAULT_VALUE_MAP = {
    100: 0,   # Trees
    200: 1,   # Lush Bushes
    300: 2,   # Dry Grass
    500: 3,   # Dry Bushes
    550: 4,   # Ground Clutter
    600: 5,   # Flowers
    700: 6,   # Logs
    800: 7,   # Rocks
    7100: 8,  # Landscape
    10000: 9, # Sky
}

DEFAULT_CLASS_NAMES = [
    "Trees",
    "Lush Bushes",
    "Dry Grass",
    "Dry Bushes",
    "Ground Clutter",
    "Flowers",
    "Logs",
    "Rocks",
    "Landscape",
    "Sky",
]

value_map = DEFAULT_VALUE_MAP.copy()
mapping_mode = "int"
n_classes = (max(value_map.values()) + 1) if value_map else 0
class_names = DEFAULT_CLASS_NAMES.copy()


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def _ensure_contiguous_mapping(parsed: dict) -> None:
    values = sorted(set(parsed.values()))
    expected = list(range(len(values)))
    if values != expected:
        raise ValueError(
            "Mapping class IDs must be contiguous and start at 0. "
            f"Found IDs: {values}"
        )


def load_value_map(mapping_json_path: str):
    """Load mask value mapping from JSON generated by generate_mask_mapping.py."""
    with open(mapping_json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    mode = data.get("mode", "int")
    raw_mapping = data.get("mapping", {})
    parsed = {}

    if mode == "rgb":
        for key, value in raw_mapping.items():
            rgb = tuple(int(x) for x in str(key).split(","))
            if len(rgb) != 3:
                raise ValueError(f"Invalid RGB key in mapping: {key}")
            parsed[rgb] = int(value)
    else:
        for key, value in raw_mapping.items():
            parsed[int(key)] = int(value)

    if not parsed:
        raise ValueError("Loaded mapping is empty")

    _ensure_contiguous_mapping(parsed)
    return parsed, mode


def infer_class_names_from_map(current_map: dict) -> list:
    if all(isinstance(k, int) for k in current_map.keys()):
        if set(current_map.keys()) == set(DEFAULT_VALUE_MAP.keys()):
            return DEFAULT_CLASS_NAMES.copy()
    return [f"Class_{idx}" for idx in range(max(current_map.values()) + 1)]


def set_value_map(new_map, mode):
    """Update global mapping settings used by mask conversion."""
    global value_map, n_classes, mapping_mode, class_names
    value_map = new_map
    mapping_mode = mode
    n_classes = (max(value_map.values()) + 1) if value_map else 0
    class_names = infer_class_names_from_map(value_map)


def convert_mask(mask: Image.Image) -> Image.Image:
    """Convert raw mask values to contiguous class IDs, unknown -> IGNORE_INDEX."""
    arr = np.array(mask)

    if mapping_mode == "rgb":
        if arr.ndim == 2:
            arr = np.stack([arr, arr, arr], axis=-1)
        if arr.shape[2] > 3:
            arr = arr[:, :, :3]

        new_arr = np.full(arr.shape[:2], IGNORE_INDEX, dtype=np.uint8)
        for raw_value, new_value in value_map.items():
            rgb = np.array(raw_value, dtype=arr.dtype)
            new_arr[np.all(arr == rgb, axis=-1)] = new_value
    else:
        if arr.ndim == 3:
            arr = arr[:, :, 0]
        new_arr = np.full(arr.shape, IGNORE_INDEX, dtype=np.uint8)
        for raw_value, new_value in value_map.items():
            new_arr[arr == raw_value] = new_value

    return Image.fromarray(new_arr)


class JointAugment:
    def __init__(self, hflip: float, vflip: float, jitter_strength: float):
        self.hflip = hflip
        self.vflip = vflip
        if jitter_strength > 0:
            self.jitter = transforms.ColorJitter(
                brightness=jitter_strength,
                contrast=jitter_strength,
                saturation=jitter_strength,
                hue=min(0.1, jitter_strength / 2.0),
            )
        else:
            self.jitter = None

    def __call__(self, image: Image.Image, mask: Image.Image):
        if self.hflip > 0 and random.random() < self.hflip:
            image = ImageOps.mirror(image)
            mask = ImageOps.mirror(mask)

        if self.vflip > 0 and random.random() < self.vflip:
            image = ImageOps.flip(image)
            mask = ImageOps.flip(mask)

        if self.jitter is not None:
            image = self.jitter(image)

        return image, mask


class MaskDataset(Dataset):
    def __init__(
        self,
        data_dir,
        image_transform,
        mask_resize,
        augment=None,
    ):
        self.root = Path(data_dir)
        self.image_dir = self.root / "Color_Images"
        self.mask_dir = self.root / "Segmentation"
        self.image_transform = image_transform
        self.mask_resize = mask_resize
        self.augment = augment

        if not self.image_dir.exists():
            raise FileNotFoundError(f"Missing folder: {self.image_dir}")
        if not self.mask_dir.exists():
            raise FileNotFoundError(f"Missing folder: {self.mask_dir}")

        image_names = {
            p.name for p in self.image_dir.iterdir() if p.is_file() and p.suffix.lower() in IMAGE_EXTS
        }
        mask_names = {
            p.name for p in self.mask_dir.iterdir() if p.is_file() and p.suffix.lower() in IMAGE_EXTS
        }
        self.data_ids = sorted(image_names & mask_names)

        if not self.data_ids:
            raise RuntimeError(f"No matching image/mask file names in {self.root}")

    def __len__(self):
        return len(self.data_ids)

    def __getitem__(self, idx):
        name = self.data_ids[idx]
        image = Image.open(self.image_dir / name).convert("RGB")
        mask = Image.open(self.mask_dir / name)
        mask = convert_mask(mask)

        if self.augment is not None:
            image, mask = self.augment(image, mask)

        image = self.image_transform(image)
        mask = self.mask_resize(mask)
        mask_arr = np.array(mask, dtype=np.uint8)
        mask_tensor = torch.from_numpy(mask_arr.astype(np.int64))

        return image, mask_tensor


class SegmentationHeadConvNeXt(nn.Module):
    def __init__(self, in_channels, out_channels, token_w, token_h):
        super().__init__()
        self.h = token_h
        self.w = token_w

        self.stem = nn.Sequential(
            nn.Conv2d(in_channels, 128, kernel_size=7, padding=3),
            nn.GELU(),
        )

        self.block = nn.Sequential(
            nn.Conv2d(128, 128, kernel_size=7, padding=3, groups=128),
            nn.GELU(),
            nn.Conv2d(128, 128, kernel_size=1),
            nn.GELU(),
        )

        self.classifier = nn.Conv2d(128, out_channels, kernel_size=1)

    def forward(self, x):
        bsz, n_tokens, channels = x.shape
        x = x.reshape(bsz, self.h, self.w, channels).permute(0, 3, 1, 2)
        x = self.stem(x)
        x = self.block(x)
        return self.classifier(x)


def update_confusion_matrix(conf_mat, pred, target, num_classes, ignore_index):
    valid = target != ignore_index
    if valid.sum() == 0:
        return conf_mat

    pred = pred[valid]
    target = target[valid]
    idx = target * num_classes + pred
    bins = torch.bincount(idx, minlength=num_classes * num_classes)
    conf_mat += bins.reshape(num_classes, num_classes).cpu().numpy().astype(np.int64)
    return conf_mat


def metrics_from_confusion(conf_mat):
    conf = conf_mat.astype(np.float64)
    tp = np.diag(conf)
    fp = conf.sum(axis=0) - tp
    fn = conf.sum(axis=1) - tp
    union = tp + fp + fn

    iou = np.divide(tp, union, out=np.full_like(tp, np.nan), where=union > 0)
    dice_den = (2.0 * tp) + fp + fn
    dice = np.divide(2.0 * tp, dice_den, out=np.full_like(tp, np.nan), where=dice_den > 0)

    total = conf.sum()
    pixel_acc = float(tp.sum() / total) if total > 0 else 0.0

    return {
        "mean_iou": float(np.nanmean(iou)),
        "mean_dice": float(np.nanmean(dice)),
        "pixel_acc": pixel_acc,
        "per_class_iou": iou.tolist(),
        "per_class_dice": dice.tolist(),
    }


def build_class_weights(mask_dir: Path, max_masks: int = 0):
    mask_paths = [
        p for p in sorted(mask_dir.iterdir()) if p.is_file() and p.suffix.lower() in IMAGE_EXTS
    ]
    if not mask_paths:
        raise RuntimeError(f"No masks found in {mask_dir}")

    if max_masks > 0:
        mask_paths = mask_paths[:max_masks]

    counts = np.zeros(n_classes, dtype=np.float64)
    for path in tqdm(mask_paths, desc="Class weights", leave=False):
        mask = convert_mask(Image.open(path))
        arr = np.array(mask, dtype=np.uint8)
        valid = arr != IGNORE_INDEX
        if np.any(valid):
            binc = np.bincount(arr[valid].astype(np.int64), minlength=n_classes)
            counts += binc

    counts[counts == 0] = 1.0
    inv_freq = counts.sum() / (n_classes * counts)
    inv_freq = inv_freq / np.mean(inv_freq)
    return torch.tensor(inv_freq.astype(np.float32))


def run_epoch(
    classifier,
    backbone,
    loader,
    optimizer,
    scaler,
    loss_fn,
    device,
    use_amp,
    train_mode,
):
    classifier.train(train_mode)
    conf_mat = np.zeros((n_classes, n_classes), dtype=np.int64)
    losses = []

    desc = "Train" if train_mode else "Val"
    loop = tqdm(loader, desc=desc, leave=False)

    for imgs, labels in loop:
        imgs = imgs.to(device, non_blocking=True)
        labels = labels.to(device, non_blocking=True)

        if train_mode:
            optimizer.zero_grad(set_to_none=True)

        with torch.no_grad():
            feats = backbone.forward_features(imgs)["x_norm_patchtokens"]

        with torch.cuda.amp.autocast(enabled=use_amp):
            logits = classifier(feats)
            logits = F.interpolate(
                logits,
                size=imgs.shape[2:],
                mode="bilinear",
                align_corners=False,
            )
            loss = loss_fn(logits, labels)

        if train_mode:
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()

        preds = torch.argmax(logits.detach(), dim=1)
        update_confusion_matrix(
            conf_mat,
            pred=preds.cpu(),
            target=labels.detach().cpu(),
            num_classes=n_classes,
            ignore_index=IGNORE_INDEX,
        )

        loss_value = float(loss.item())
        losses.append(loss_value)
        loop.set_postfix(loss=f"{loss_value:.4f}")

    metrics = metrics_from_confusion(conf_mat)
    mean_loss = float(np.mean(losses)) if losses else 0.0
    return mean_loss, metrics


def save_training_plots(history: dict, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    plt.figure(figsize=(13, 9))

    plt.subplot(2, 2, 1)
    plt.plot(history["epoch"], history["train_loss"], label="Train")
    plt.plot(history["epoch"], history["val_loss"], label="Val")
    plt.title("Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.grid(True)
    plt.legend()

    plt.subplot(2, 2, 2)
    plt.plot(history["epoch"], history["train_iou"], label="Train")
    plt.plot(history["epoch"], history["val_iou"], label="Val")
    plt.title("Mean IoU")
    plt.xlabel("Epoch")
    plt.ylabel("IoU")
    plt.grid(True)
    plt.legend()

    plt.subplot(2, 2, 3)
    plt.plot(history["epoch"], history["train_dice"], label="Train")
    plt.plot(history["epoch"], history["val_dice"], label="Val")
    plt.title("Mean Dice")
    plt.xlabel("Epoch")
    plt.ylabel("Dice")
    plt.grid(True)
    plt.legend()

    plt.subplot(2, 2, 4)
    plt.plot(history["epoch"], history["train_pixel_acc"], label="Train")
    plt.plot(history["epoch"], history["val_pixel_acc"], label="Val")
    plt.title("Pixel Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.grid(True)
    plt.legend()

    plt.tight_layout()
    plt.savefig(output_dir / "training_curves.png")
    plt.close()


def save_history(history: dict, output_dir: Path, best_epoch: int) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    csv_path = output_dir / "history.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "epoch",
            "lr",
            "train_loss",
            "val_loss",
            "train_iou",
            "val_iou",
            "train_dice",
            "val_dice",
            "train_pixel_acc",
            "val_pixel_acc",
        ])
        for i in range(len(history["epoch"])):
            writer.writerow([
                history["epoch"][i],
                history["lr"][i],
                history["train_loss"][i],
                history["val_loss"][i],
                history["train_iou"][i],
                history["val_iou"][i],
                history["train_dice"][i],
                history["val_dice"][i],
                history["train_pixel_acc"][i],
                history["val_pixel_acc"][i],
            ])

    payload = {
        "best_epoch": best_epoch,
        "history": history,
    }
    with (output_dir / "history.json").open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


def parse_args():
    script_dir = Path(__file__).resolve().parent

    parser = argparse.ArgumentParser(description="Train segmentation model")
    parser.add_argument(
        "--train_dir",
        type=str,
        default=str(script_dir / ".." / "Offroad_Segmentation_Training_Dataset" / "train"),
    )
    parser.add_argument(
        "--val_dir",
        type=str,
        default=str(script_dir / ".." / "Offroad_Segmentation_Training_Dataset" / "val"),
    )
    parser.add_argument("--output_dir", type=str, default=str(script_dir / "train_stats"))
    parser.add_argument(
        "--mapping_json",
        type=str,
        default="",
        help="Optional mapping JSON generated by generate_mask_mapping.py",
    )

    parser.add_argument("--batch_size", type=int, default=2)
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--lr", type=float, default=3e-4)
    parser.add_argument("--weight_decay", type=float, default=1e-4)
    parser.add_argument("--num_workers", type=int, default=0)
    parser.add_argument("--seed", type=int, default=42)

    parser.add_argument(
        "--backbone_size",
        type=str,
        default="small",
        choices=["small", "base", "large", "giant"],
    )
    parser.add_argument("--optimizer", type=str, default="adamw", choices=["adamw", "sgd"])
    parser.add_argument("--scheduler", type=str, default="cosine", choices=["cosine", "none"])
    parser.add_argument("--early_stop_patience", type=int, default=8)
    parser.add_argument("--amp", type=int, default=1, choices=[0, 1])

    parser.add_argument(
        "--class_weighting",
        type=str,
        default="auto",
        choices=["auto", "none"],
    )
    parser.add_argument(
        "--max_weight_masks",
        type=int,
        default=0,
        help="0 means use all train masks while estimating class weights",
    )

    parser.add_argument("--aug_hflip", type=float, default=0.5)
    parser.add_argument("--aug_vflip", type=float, default=0.0)
    parser.add_argument("--aug_color_jitter", type=float, default=0.2)
    parser.add_argument("--disable_augmentation", action="store_true")

    return parser.parse_args()


def main():
    args = parse_args()
    set_seed(args.seed)

    if args.mapping_json:
        loaded_map, loaded_mode = load_value_map(args.mapping_json)
        set_value_map(loaded_map, loaded_mode)
        print(f"Loaded mapping from {args.mapping_json} | mode={mapping_mode} | classes={n_classes}")
    else:
        print(f"Using default Falcon mapping | mode={mapping_mode} | classes={n_classes}")

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    use_amp = bool(args.amp) and device.type == "cuda"

    print(f"Using device: {device}")
    print(f"AMP enabled: {use_amp}")

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    checkpoint_dir = output_dir / "checkpoints"
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    w = int(((960 / 2) // 14) * 14)
    h = int(((540 / 2) // 14) * 14)

    image_transform = transforms.Compose([
        transforms.Resize((h, w)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
    ])
    mask_resize = transforms.Resize((h, w), interpolation=transforms.InterpolationMode.NEAREST)

    augment = None
    if not args.disable_augmentation:
        augment = JointAugment(
            hflip=args.aug_hflip,
            vflip=args.aug_vflip,
            jitter_strength=args.aug_color_jitter,
        )

    print(f"Train dir: {args.train_dir}")
    print(f"Val dir:   {args.val_dir}")

    trainset = MaskDataset(
        data_dir=args.train_dir,
        image_transform=image_transform,
        mask_resize=mask_resize,
        augment=augment,
    )
    valset = MaskDataset(
        data_dir=args.val_dir,
        image_transform=image_transform,
        mask_resize=mask_resize,
        augment=None,
    )

    pin_memory = device.type == "cuda"
    train_loader = DataLoader(
        trainset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=pin_memory,
    )
    val_loader = DataLoader(
        valset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=pin_memory,
    )

    print(f"Training samples: {len(trainset)}")
    print(f"Validation samples: {len(valset)}")

    print("Loading DINOv2 backbone...")
    backbone_archs = {
        "small": "vits14",
        "base": "vitb14_reg",
        "large": "vitl14_reg",
        "giant": "vitg14_reg",
    }
    backbone_name = f"dinov2_{backbone_archs[args.backbone_size]}"
    backbone = torch.hub.load("facebookresearch/dinov2", backbone_name)
    backbone.to(device).eval()
    print(f"Backbone loaded: {backbone_name}")

    sample_imgs, _ = next(iter(train_loader))
    sample_imgs = sample_imgs.to(device)
    with torch.no_grad():
        emb = backbone.forward_features(sample_imgs)["x_norm_patchtokens"]
    n_embedding = emb.shape[2]
    print(f"Embedding dimension: {n_embedding}")

    classifier = SegmentationHeadConvNeXt(
        in_channels=n_embedding,
        out_channels=n_classes,
        token_w=w // 14,
        token_h=h // 14,
    ).to(device)

    class_weights = None
    if args.class_weighting == "auto":
        class_weights = build_class_weights(
            mask_dir=Path(args.train_dir) / "Segmentation",
            max_masks=args.max_weight_masks,
        ).to(device)
        print("Auto class weights:", class_weights.detach().cpu().numpy().round(3).tolist())

    loss_fn = nn.CrossEntropyLoss(weight=class_weights, ignore_index=IGNORE_INDEX)

    if args.optimizer == "adamw":
        optimizer = AdamW(classifier.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    else:
        optimizer = SGD(classifier.parameters(), lr=args.lr, momentum=0.9, weight_decay=args.weight_decay)

    scheduler = None
    if args.scheduler == "cosine":
        scheduler = CosineAnnealingLR(optimizer, T_max=args.epochs)

    scaler = torch.cuda.amp.GradScaler(enabled=use_amp)

    history = {
        "epoch": [],
        "lr": [],
        "train_loss": [],
        "val_loss": [],
        "train_iou": [],
        "val_iou": [],
        "train_dice": [],
        "val_dice": [],
        "train_pixel_acc": [],
        "val_pixel_acc": [],
    }

    best_val_iou = -1.0
    best_epoch = 0
    epochs_without_improve = 0
    best_path = checkpoint_dir / "best_segmentation_head.pth"
    last_path = checkpoint_dir / "last_segmentation_head.pth"

    print("\nStarting training...")
    print("=" * 80)

    for epoch in range(1, args.epochs + 1):
        train_loss, train_metrics = run_epoch(
            classifier=classifier,
            backbone=backbone,
            loader=train_loader,
            optimizer=optimizer,
            scaler=scaler,
            loss_fn=loss_fn,
            device=device,
            use_amp=use_amp,
            train_mode=True,
        )

        with torch.no_grad():
            val_loss, val_metrics = run_epoch(
                classifier=classifier,
                backbone=backbone,
                loader=val_loader,
                optimizer=optimizer,
                scaler=scaler,
                loss_fn=loss_fn,
                device=device,
                use_amp=use_amp,
                train_mode=False,
            )

        if scheduler is not None:
            scheduler.step()

        lr_now = float(optimizer.param_groups[0]["lr"])

        history["epoch"].append(epoch)
        history["lr"].append(lr_now)
        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["train_iou"].append(train_metrics["mean_iou"])
        history["val_iou"].append(val_metrics["mean_iou"])
        history["train_dice"].append(train_metrics["mean_dice"])
        history["val_dice"].append(val_metrics["mean_dice"])
        history["train_pixel_acc"].append(train_metrics["pixel_acc"])
        history["val_pixel_acc"].append(val_metrics["pixel_acc"])

        print(
            f"Epoch {epoch:03d}/{args.epochs:03d} | "
            f"train_loss={train_loss:.4f} val_loss={val_loss:.4f} | "
            f"val_iou={val_metrics['mean_iou']:.4f} val_dice={val_metrics['mean_dice']:.4f} "
            f"val_acc={val_metrics['pixel_acc']:.4f} lr={lr_now:.6f}"
        )

        torch.save(classifier.state_dict(), last_path)

        improved = val_metrics["mean_iou"] > best_val_iou
        if improved:
            best_val_iou = val_metrics["mean_iou"]
            best_epoch = epoch
            epochs_without_improve = 0
            torch.save(classifier.state_dict(), best_path)
        else:
            epochs_without_improve += 1

        if args.early_stop_patience > 0 and epochs_without_improve >= args.early_stop_patience:
            print(
                "Early stopping triggered: "
                f"no val IoU improvement for {args.early_stop_patience} epochs."
            )
            break

    save_training_plots(history, output_dir)
    save_history(history, output_dir, best_epoch=best_epoch)

    if best_path.exists():
        best_state = torch.load(best_path, map_location="cpu")
    else:
        best_state = classifier.state_dict()

    script_dir = Path(__file__).resolve().parent
    final_export_path = script_dir / "segmentation_head.pth"
    torch.save(best_state, final_export_path)

    class_names_path = output_dir / "class_names.json"
    with class_names_path.open("w", encoding="utf-8") as f:
        json.dump(class_names, f, indent=2)

    class_names_root_path = script_dir / "class_names.json"
    with class_names_root_path.open("w", encoding="utf-8") as f:
        json.dump(class_names, f, indent=2)

    summary = {
        "best_epoch": best_epoch,
        "best_val_iou": best_val_iou,
        "epochs_ran": len(history["epoch"]),
        "model_export": str(final_export_path),
        "best_checkpoint": str(best_path),
        "last_checkpoint": str(last_path),
        "class_names_output": str(class_names_path),
        "class_names_root": str(class_names_root_path),
    }
    with (output_dir / "training_summary.json").open("w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    print("\nTraining complete!")
    print(f"Best epoch: {best_epoch}")
    print(f"Best val IoU: {best_val_iou:.4f}")
    print(f"Best checkpoint: {best_path}")
    print(f"Exported model for inference: {final_export_path}")


if __name__ == "__main__":
    main()
